---
abstract: 'Utility functions for renaming a module distribution'
author:
  - 'Mike Schilli <cpan@perlmeister.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Rename
no_index:
  directory:
    - t
    - inc
requires:
  Log::Log4perl: 0.47
  Sysadm::Install: 0.14
resources:
  repository: http://github.com/mschilli/module-rename-perl.git
version: 0.04
